import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { FooterSection } from "@/components/FooterSection";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${inter.className}  dark h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <main>{children}</main>

        <FooterSection></FooterSection>
      </body>
    </html>
  );
}
